language: java

jdk:
  - oraclejdk7

script: gradle jar

branches:
  only:
    - master

before_deploy:
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-0.1.$TRAVIS_BUILD_NUMBER
  - git tag $GIT_TAG -a -m "Generated tag from TravisCI for build $TRAVIS_BUILD_NUMBER"
  - git push -q https://$GITHUB_OAUTH_KEY@github.com/felipead/cassandra-logger --tags

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: [redacted]
  file:
    - "build/libs/cassandra-logger.jar"
  on:
    tags: false
    all_branches: true

branches:
  except:
    - /^*-v[0-9]/